# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTkzODVkNzUxNDBiMjI1NmYzODE4NTJhNmE2MzRhOGQ2MDMyNjYzOTVkMjE4YTU3ZmEyNTliMzczYjVlNjY4ZDRhODA3MDdmNjgxYjM5NGVkZWQ4NWM2ZTY3Mjc1MWNiYTVkZmY1Yzg2MWUwYjYwODJkZmJlNTg3N2I3YmE5ODk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
